name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      database_hostname: postgres
      database_port: 5432
      database_password: password123
      database_name: fastapi
      database_username: postgres
      secret_key: O0xgalEUTGvDNgoArVxndbzexqpCR2mQ
      algorithm: HS256
      access_token_expire_minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v6
      - name: install python version 3.13
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest